import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { GameProvider } from "@/contexts/games";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Nav />
          <main className="flex min-h-screen flex-col items-center justify-between py-16 px-8 sm:px-12 lg:px-16 xl:px-24 bg-dark_grey">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
